target = "res/libTTapp.so"

[[unit]]
path = "nu2api.saga/numath/nuvec.c"
symbols = [
    "NuVecAdd",
    "NuVecSub",
    "NuVecScale",
    "NuVecAddScale",
    "NuVecScaleAccum",
    "NuVecInvScale",
    "NuVecCross",
    "NuVecCrossRel",
    "NuVecDot",
    "NuVecMax",
    "NuVecMin",
    "NuVecMagSqr",
    "NuVecMag",
    "NuVecMagXZ",
    "NuVecNorm",
    "NuVecSurfaceNormal",
    "NuVecDist",
    "NuVecDistSqr",
    "NuVecXZDist",
    "NuVecXZDistSqr",
    "NuVecLerp",
    "NuVecCompareTolerance",
]

[[unit]]
path = "nu2api.saga/numath/nufloat.c"
symbols = [
    "NuFabs",
    "NuFnabs",
    "NuFneg",
    "NuFsign",
    "NuFsqrt",
]

[[unit]]
path = "nu2api.saga/numath/numtx.c"
symbols = [
    "numtx_zero",
    "numtx_identity",
    "NuMtxSetZero",
    "NuMtxSetIdentity",
    "NuMtxSetTranslation",
    "NuMtxSetTranslationNeg",
    "NuMtxSetScale",
]

[[unit]]
path = "nu2api.saga/numath/nutrig_gen.cpp"
symbols = [
    "NuTrigTable",
    "NuTrigInit",
]

[[unit]]
path = "nu2api.saga/nucore/nustring.c"
symbols = [
    "NuStrCat",
    "NuStrCatW",
    "NuStrChr",
    "NuStrChrW",
    "NuStrCmp",
    "NuStrCmpW",
    "NuStrCpy",
    "NuStrCpyW",
    "NuStrCpyWC",
    "NuStrFindPosU",
    "NuStrFixExt",
    "NuStrFixExtPlatform",
    "NuStrGetExt",
    "NuStrGetFilenameNoExt",
    "NuStrGetPath",
    "NuStrICmp",
    "NuStrICmpW",
    "NuStrICmpWC",
    "NuStrIStr",
    "NuStrIStrW",
    "NuStrLen",
    "NuStrLenU",
    "NuStrLenW",
    "NuStrLwr",
    "NuStrLwrW",
    "NuStrNCat",
    "NuStrNCatW",
    "NuStrNCmp",
    "NuStrNCmpW",
    "NuStrNCpy",
    "NuStrNCpyW",
    "NuStrNICmp",
    "NuStrNICmpW",
    "NuStrRChr",
    "NuStrRChrW",
    "NuStrStrW",
    "NuStrSubstituteString",
    "NuStrToL",
    "NuStrToLower",
    "NuStrToLW",
    "NuStrTrap",
    "NuStrUpr",
    "NuStrUprW",
    "NuToLower",
    "NuToUpper",
]
