ignore = [
    "_Z14NuXboxLiveInitv",
    "Nu360GetCommandLine",
    "_Z24Nu360ConfigureSMBSharingPPc",
    "NuVecMtxTranslate",
    "NuVecMtxRotateValX",
    "NuVecMtxRotateValY",
    "NuVecMtxRotateValZ",
    "NuVecMtxRotateH",
    "NuVecMtxScale",
    "NuVecInvMtxTranslate",
    "NuVecInvMtxRotateValX",
    "NuVecInvMtxRotateValY",
    "NuVecInvMtxRotateValZ",
    "NuVecInvMtxScale",
    "NuVecRotateYValX",
    "NuVecInvScale",
    "NuVecCrossRel",
    "NuVecMagXZ",
    "NuVecCompareTolerance",
    "NuVec4ScaleAccum",
    "NuVec4Sub",
    "NuVec4Max",
    "NuVec4Min",
    "NuVec4Mag",
    "NuVec4MagSqr",
    "NuVec4Lerp",
    "NuVec4ToNuHalfVec4",
    "NuHalfVec4ToNuVec4",
    "NuVecConvertToIntVU0",
    "NuVec4MtxTransformVU0x2",
    "NuVec4MtxTransformVU0x4",
    "NuVecInvMtxTransformVU0",
    "_Z11NuVecToRGBAP7nuvec_sf",
    "NuVecNormVU0",
    "NuVec4MtxInvTransformVU0",
    "NuVec4MtxInvRotVU0",
    "NuVecDiffVU0",
    "NuVecDiffSqrVU0",
    "_Z26NuFramebuffer360BeginZPassi",
    "_Z24NuFramebuffer360EndZPassv",
    "_Z24NuFramebuffer360HasZPassv",
    "_Z28NuFramebuffer360GetTileCountP15nuframebuffer_s",
    "NuRenderContext360BeginGameTime",
    "NuRenderContext360EndGameTime",
    "NuEffectTex360Create2D_aliased",
    "NuEffectTex360Create3D_aliased",
    "_Z29NuShaderObject360LoadPackFilePcP9variptr_uS0_",
    "_Z27NuShaderObject360LoadShaderP16nushaderobject_s",
    "_Z29NuShaderObject360UnloadShaderP16nushaderobject_s",
    "_Z17NuPs2PadSetMotorsP7nupad_sii",
    "NuWaterReset",
    "_Z16NuPs2GetLanguagev",
    "_Z15NuPs2PadDemoEndv",
    "_ZN11ClassEditor9ReadBlockEP7DATAPTR",
    "_ZN11ClassEditor10WriteBlockEi",
    "_ZN11ClassEditor10ClearLevelEi",
    "_ZN11ClassEditor5FlushEv",
    "_ZN11ClassEditor5EnterEv",
    "_ZN11ClassEditor4ExitEv",
    "_ZN9EdControl7RefreshEv",
    "_ZN9EdControl15SetMenuItemAttrEiP10eduiitem_sP11eduiiattr_sS3_",
    "_ZN16EdClassInterface13GetNextObjectEPvPFiS0_E",
    "_ZN22EdSpecialObjectControl7ProcessER14EdInputContext",
    "_ZN10KnotHelper13GetNumObjectsEv",
    "_ZN10KnotHelper13DestroyObjectEPvi",
    "_ZN11ClassEditor12AddMenuItemsEP10eduimenu_s",
    "_ZN10KnotHelper13GetNextObjectEPv",
    "_ZN10KnotHelper6RenderEPvi",
    "_ZN22EdSpecialObjectControl6RenderEv",
    "_ZN10KnotHelper7ProcessEPvR14EdInputContext",
    "_ZN11ClassEditor10InitialiseER9variptr_uS1_i",
    "_ZN11ClassEditor7ProcessER14EdInputContext",
    "_ZN11ClassEditor6RenderEv",
    "_ZN22EdSpecialObjectControl11AddMenuItemEP10eduimenu_sP5EdRefPv",
    "_ZN10KnotHelper12CreateObjectEPvii",
    "_ZN11ClassEditor9SerialiseER8EdStream",
    "_ZN16EdClassInterface10ClearLevelEi",
    "_ZN16EdClassInterface13DefunctObjectEPv",
    "_ZN16EdClassInterface12ReviveObjectEPv",
    "_ZN16EdClassInterface13SetObjectGuidEPvi",
    "_ZN16EdClassInterface13GetObjectGuidEPv",
    "_ZN16EdClassInterface18GetConstructorDataEPvS0_i",
    "_ZN16EdClassInterface9ConstructEPvS0_",
    "_ZN11ClassEditorD1Ev",
    "_ZN11ClassEditor7GetNameEv",
    "_ZN10KnotHelper5FlushEv",
    "_ZN10KnotHelperD1Ev",
    "_ZN22EdSpecialObjectControlD1Ev",
    "_ZN22EdSpecialObjectControlD0Ev",
    "_ZN10KnotHelperD0Ev",
    "_ZN11ClassEditorD0Ev",
]
