ignore = [
    "_Z14NuXboxLiveInitv",
    "Nu360GetCommandLine",
    "_Z24Nu360ConfigureSMBSharingPPc",
    "NuVecMtxTranslate",
    "NuVecMtxRotateValX",
    "NuVecMtxRotateValY",
    "NuVecMtxRotateValZ",
    "NuVecMtxRotateH",
    "NuVecMtxScale",
    "NuVecInvMtxTranslate",
    "NuVecInvMtxRotateValX",
    "NuVecInvMtxRotateValY",
    "NuVecInvMtxRotateValZ",
    "NuVecInvMtxScale",
    "NuVecRotateYValX",
    "NuVecInvScale",
    "NuVecCrossRel",
    "NuVecMagXZ",
    "NuVecCompareTolerance",
    "NuVec4ScaleAccum",
    "NuVec4Sub",
    "NuVec4Max",
    "NuVec4Min",
    "NuVec4Mag",
    "NuVec4MagSqr",
    "NuVec4Lerp",
    "NuVec4ToNuHalfVec4",
    "NuHalfVec4ToNuVec4",
    "NuVecConvertToIntVU0",
    "NuVec4MtxTransformVU0x2",
    "NuVec4MtxTransformVU0x4",
    "NuVecInvMtxTransformVU0",
    "_Z11NuVecToRGBAP7nuvec_sf",
    "NuVecNormVU0",
    "NuVec4MtxInvTransformVU0",
    "NuVec4MtxInvRotVU0",
    "NuVecDiffVU0",
    "NuVecDiffSqrVU0",
    "_Z26NuFramebuffer360BeginZPassi",
    "_Z24NuFramebuffer360EndZPassv",
    "_Z24NuFramebuffer360HasZPassv",
    "_Z28NuFramebuffer360GetTileCountP15nuframebuffer_s",
    "NuRenderContext360BeginGameTime",
    "NuRenderContext360EndGameTime",
    "NuEffectTex360Create2D_aliased",
    "NuEffectTex360Create3D_aliased",
    "_Z29NuShaderObject360LoadPackFilePcP9variptr_uS0_",
    "_Z27NuShaderObject360LoadShaderP16nushaderobject_s",
    "_Z29NuShaderObject360UnloadShaderP16nushaderobject_s",
    "_Z17NuPs2PadSetMotorsP7nupad_sii",
    "NuWaterReset",
    "_Z16NuPs2GetLanguagev",
    "_Z15NuPs2PadDemoEndv",
    "_ZL6InitUIv",
    "_ZL9edrtlInitv",
    "_ZN11ClassEditor9ReadBlockEP7DATAPTR",
    "_ZN11ClassEditor10WriteBlockEi",
    "_ZN11ClassEditor10ClearLevelEi",
    "_ZN11ClassEditor5FlushEv",
    "_ZN11ClassEditor5EnterEv",
    "_ZN11ClassEditor4ExitEv",
    "_ZN9EdControl7RefreshEv",
    "_ZN9EdControl15SetMenuItemAttrEiP10eduiitem_sP11eduiiattr_sS3_",
    "_ZN16EdClassInterface13GetNextObjectEPvPFiS0_E",
    "_ZN22EdSpecialObjectControl7ProcessER14EdInputContext",
    "_ZN10KnotHelper13GetNumObjectsEv",
    "_ZN10KnotHelper13DestroyObjectEPvi",
    "_ZN11ClassEditor12AddMenuItemsEP10eduimenu_s",
    "_ZN10KnotHelper13GetNextObjectEPv",
    "_ZN10KnotHelper6RenderEPvi",
    "_ZN22EdSpecialObjectControl6RenderEv",
    "_ZN10KnotHelper7ProcessEPvR14EdInputContext",
    "_ZN11ClassEditor10InitialiseER9variptr_uS1_i",
    "_ZN11ClassEditor7ProcessER14EdInputContext",
    "_ZN11ClassEditor6RenderEv",
    "_ZN22EdSpecialObjectControl11AddMenuItemEP10eduimenu_sP5EdRefPv",
    "_ZN10KnotHelper12CreateObjectEPvii",
    "_ZN11ClassEditor9SerialiseER8EdStream",
    "_ZN16EdClassInterface10ClearLevelEi",
    "_ZN16EdClassInterface13DefunctObjectEPv",
    "_ZN16EdClassInterface12ReviveObjectEPv",
    "_ZN16EdClassInterface13SetObjectGuidEPvi",
    "_ZN16EdClassInterface13GetObjectGuidEPv",
    "_ZN16EdClassInterface18GetConstructorDataEPvS0_i",
    "_ZN16EdClassInterface9ConstructEPvS0_",
    "_ZN11ClassEditorD1Ev",
    "_ZN11ClassEditor7GetNameEv",
    "_ZN10KnotHelper5FlushEv",
    "_ZN10KnotHelperD1Ev",
    "_ZN22EdSpecialObjectControlD1Ev",
    "_ZN22EdSpecialObjectControlD0Ev",
    "_ZN10KnotHelperD0Ev",
    "_ZN11ClassEditorD0Ev",
]

[extra_units]
ogg_vorbis = [
    "ov_bitrate",
    "ov_bitrate_instant",
    "ov_clear",
    "ov_comment",
    "ov_crosslap",
    "ov_fopen",
    "ov_halfrate",
    "ov_halfrate_p",
    "ov_info",
    "ov_open",
    "ov_open_callbacks",
    "ov_pcm_seek",
    "ov_pcm_seek_lap",
    "ov_pcm_seek_page",
    "ov_pcm_seek_page_lap",
    "ov_pcm_tell",
    "ov_pcm_total",
    "ov_raw_seek",
    "ov_raw_seek_lap",
    "ov_raw_tell",
    "ov_raw_total",
    "ov_read",
    "ov_read_filter",
    "ov_read_float",
    "ov_seekable",
    "ov_serialnumber",
    "ov_streams",
    "ov_test",
    "ov_test_callbacks",
    "ov_test_open",
    "ov_time_seek",
    "ov_time_seek_lap",
    "ov_time_seek_page",
    "ov_time_seek_page_lap",
    "ov_time_tell",
    "ov_time_total",

    "_Z12ov_time_seekP14OggVorbis_Filed",
    "_Z11ov_pcm_seekP14OggVorbis_Filex",
    "_Z17ov_open_callbacksPvP14OggVorbis_FilePKcl12ov_callbacks",
    "_Z7ov_infoP14OggVorbis_Filei",
    "_Z12ov_pcm_totalP14OggVorbis_Filei",
    "_Z13ov_time_totalP14OggVorbis_Filei",
    "_Z8ov_clearP14OggVorbis_File",
    "_Z7ov_readP14OggVorbis_FilePciiiiPi",
    "_Z11ov_raw_seekP14OggVorbis_Filex",
    "_Z13ov_halfrate_pP14OggVorbis_File",
    "_Z17ov_test_callbacksPvP14OggVorbis_FilePKcl12ov_callbacks",
    "_Z7ov_testP7__sFILEP14OggVorbis_FilePKcl",
    "_Z10ov_streamsP14OggVorbis_File",
    "_Z11ov_seekableP14OggVorbis_File",
    "_Z18ov_bitrate_instantP14OggVorbis_File",
    "_Z15ov_serialnumberP14OggVorbis_Filei",
    "_Z12ov_raw_totalP14OggVorbis_Filei",
    "_Z12ov_test_openP14OggVorbis_File",
    "_Z7ov_openP7__sFILEP14OggVorbis_FilePKcl",
    "_Z8ov_fopenPKcP14OggVorbis_File",
    "_Z16ov_pcm_seek_pageP14OggVorbis_Filex",
    "_Z11ov_halfrateP14OggVorbis_Filei",
    "_Z17ov_time_seek_pageP14OggVorbis_Filed",
    "_Z10ov_bitrateP14OggVorbis_Filei",
    "_Z11ov_raw_tellP14OggVorbis_File",
    "_Z11ov_pcm_tellP14OggVorbis_File",
    "_Z12ov_time_tellP14OggVorbis_File",
    "_Z10ov_commentP14OggVorbis_Filei",
    "_Z14ov_read_filterP14OggVorbis_FilePciiiiPiPFvPPfllPvES5_",
    "_Z13ov_read_floatP14OggVorbis_FilePPPfiPi",
    "_Z11ov_crosslapP14OggVorbis_FileS0_",
    "_Z15ov_raw_seek_lapP14OggVorbis_Filex",
    "_Z15ov_pcm_seek_lapP14OggVorbis_Filex",
    "_Z20ov_pcm_seek_page_lapP14OggVorbis_Filex",
    "_Z16ov_time_seek_lapP14OggVorbis_Filed",
    "_Z21ov_time_seek_page_lapP14OggVorbis_Filed",
]
